{
 "title": "E-Com 360: Postgres & Redis",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "category",
    "query": "SELECT DISTINCT category_level1 FROM public.raw_events WHERE category_level1 IS NOT NULL;"
   }
  ]
 },
 "panels": [
  {
   "title": "--- POSTGRES: TRANSACTIONAL INSIGHTS ---",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "The Conversion Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecommerce",
     "rawSql": "SELECT \r\n    COUNT(*) AS total_events,\r\n    COUNT(*) FILTER (WHERE event_type = 'purchase') AS total_purchases,\r\n    ROUND(\r\n        (COUNT(*) FILTER (WHERE event_type = 'purchase')::NUMERIC / \r\n        NULLIF(COUNT(*), 0)) * 100, \r\n    2) AS conversion_rate_percentage\r\nFROM public.raw_events\r\nWHERE $__timeFilter(event_time);"
    }
   ]
  },
  {
   "title": "Brand Market Share",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecommerce",
     "rawSql": "SELECT \r\n    brand, \r\n    COUNT(*) as \"value\"\r\nFROM public.raw_events\r\nWHERE $__timeFilter(event_time) -- Ensures sync with your dashboard's time picker\r\n  AND event_type = 'purchase' \r\n  AND brand IS NOT NULL\r\nGROUP BY brand\r\nORDER BY value DESC\r\nLIMIT 8;"
    }
   ]
  },
  {
   "title": "Monthly Revenue ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  DATE_TRUNC('month', event_time) AS \"time\", \r\n  SUM(price) AS \"Total Revenue\" \r\nFROM public.raw_events \r\nWHERE event_type = 'purchase' \r\n  AND $__timeFilter(event_time)\r\nGROUP BY 1 \r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Price Distribution Histogram",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN price < 50 THEN '1. Budget (<$50)'\r\n    WHEN price BETWEEN 50 AND 150 THEN '2. Entry ($50-$150)'\r\n    WHEN price BETWEEN 150 AND 500 THEN '3. Mid-Range ($150-$500)'\r\n    WHEN price BETWEEN 500 AND 1000 THEN '4. Premium ($500-$1000)'\r\n    ELSE '5. Luxury ($1000+)'\r\n  END AS \"Price Tier\",\r\n  COUNT(*) AS \"Total Purchases\"\r\nFROM public.raw_events\r\nWHERE event_type = 'purchase'\r\n  AND category_level1 IN ($category) -- This links the dropdown to the chart\r\n  AND $__timeFilter(event_time)\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Category Revenue Leaderboard",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecommerce",
     "rawSql": "SELECT \r\n    category_level1 AS \"Product Category\",\r\n    SUM(price) AS \"Revenue\"\r\nFROM public.raw_events\r\nWHERE event_type = 'purchase' \r\n  AND category_level1 IS NOT NULL\r\n  AND $__timeFilter(event_time)\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 7;"
    }
   ]
  },
  {
   "title": "The \"Daily Comparison\"",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  TO_CHAR(event_time, 'Day') AS \"Day of Week\",\r\n  EXTRACT(DOW FROM event_time) AS \"dow_index\",\r\n  COUNT(*) AS \"Event Count\"\r\nFROM public.raw_events\r\nWHERE $__timeFilter(event_time)\r\nGROUP BY 1, 2\r\nORDER BY 2 ASC;"
    }
   ]
  },
  {
   "title": "Real-Time Revenue Volatility",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "dataset": "ecommerce",
     "rawSql": "WITH daily_stats AS (\r\n  SELECT\r\n    $__timeGroup(event_time, '1h') AS \"time\", -- Grouping by 1 hour instead of 1 minute\r\n    AVG(price) as avg_p,\r\n    MAX(price) as max_p\r\n  FROM public.raw_events\r\n  WHERE event_type = 'purchase'\r\n    AND $__timeFilter(event_time)\r\n  GROUP BY 1\r\n)\r\nSELECT\r\n  \"time\",\r\n  -- Using a window function to smooth the line across neighboring hours\r\n  AVG(avg_p) OVER (ORDER BY \"time\" ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS \"Average Sale Trend\",\r\n  MAX(max_p) OVER (ORDER BY \"time\" ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS \"Peak Price Trend\"\r\nFROM daily_stats\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Live Purchase Stream",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT event_time, brand, price, category_level2 FROM raw_events WHERE event_type='purchase' ORDER BY event_time DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "--- REDIS: REAL-TIME ML & USER STATE ---",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Live Prediction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "xrange",
     "end": "+",
     "keyName": "stream:ml_metrics",
     "start": "-",
     "streamingDataType": "DataFrame",
     "type": "command"
    }
   ]
  },
  {
   "title": "Number of Prediction",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "xlen", "keyName": "stream:ml_metrics", "streamingDataType": "DataFrame", "type": "command" }
   ]
  }
 ]
}